
#include "nuitka/prelude.h"

// Sentinel PyObject to be used for all our call iterator endings. It will
// become a PyCObject pointing to NULL. It's address is unique, and that's
// enough for us to use it as sentinel value.
PyObject *_sentinel_value = NULL;

PyObject *const_int_0;
PyObject *const_str_dot;
PyObject *const_int_neg_1;
PyObject *const_int_pos_1;
PyObject *const_int_pos_2;
PyObject *const_int_pos_6;
PyObject *const_int_pos_7;
PyObject *const_int_pos_8;
PyObject *const_str_empty;
PyObject *const_str_space;
PyObject *const_dict_empty;
PyObject *const_int_pos_16;
PyObject *const_int_pos_65;
PyObject *const_xrange_0_8;
PyObject *const_bytes_empty;
PyObject *const_str_newline;
PyObject *const_str_plain_Q;
PyObject *const_str_plain_R;
PyObject *const_str_plain_W;
PyObject *const_str_plain_a;
PyObject *const_str_plain_b;
PyObject *const_str_plain_c;
PyObject *const_str_plain_i;
PyObject *const_str_plain_j;
PyObject *const_str_plain_k;
PyObject *const_str_plain_n;
PyObject *const_str_plain_r;
PyObject *const_tuple_empty;
PyObject *const_str_plain_am;
PyObject *const_str_plain_os;
PyObject *const_str_plain_pc;
PyObject *const_str_plain_rb;
PyObject *const_str_plain_col;
PyObject *const_str_plain_des;
PyObject *const_str_plain_end;
PyObject *const_str_plain_int;
PyObject *const_str_plain_len;
PyObject *const_str_plain_pop;
PyObject *const_str_plain_r_c;
PyObject *const_str_plain_row;
PyObject *const_str_plain_sum;
PyObject *const_str_plain_Grid;
PyObject *const_str_plain_King;
PyObject *const_str_plain_Pawn;
PyObject *const_str_plain_Rook;
PyObject *const_str_plain_copy;
PyObject *const_str_plain_file;
PyObject *const_str_plain_iter;
PyObject *const_str_plain_king;
PyObject *const_str_plain_move;
PyObject *const_str_plain_name;
PyObject *const_str_plain_none;
PyObject *const_str_plain_open;
PyObject *const_str_plain_pawn;
PyObject *const_str_plain_read;
PyObject *const_str_plain_repr;
PyObject *const_str_plain_rook;
PyObject *const_str_plain_scan;
PyObject *const_str_plain_self;
PyObject *const_str_plain_send;
PyObject *const_str_plain_site;
PyObject *const_str_plain_turn;
PyObject *const_str_plain_type;
PyObject *const_str_plain_False;
PyObject *const_str_plain_Piece;
PyObject *const_str_plain_Queen;
PyObject *const_str_plain_black;
PyObject *const_str_plain_board;
PyObject *const_str_plain_bytes;
PyObject *const_str_plain_clear;
PyObject *const_str_plain_close;
PyObject *const_str_plain_color;
PyObject *const_str_plain_input;
PyObject *const_str_plain_label;
PyObject *const_str_plain_level;
PyObject *const_str_plain_piece;
PyObject *const_str_plain_print;
PyObject *const_str_plain_queen;
PyObject *const_str_plain_range;
PyObject *const_str_plain_throw;
PyObject *const_str_plain_types;
PyObject *const_str_plain_uGrid;
PyObject *const_str_plain_upper;
PyObject *const_str_plain_utils;
PyObject *const_str_plain_white;
PyObject *const_str_plain_Bishop;
PyObject *const_str_plain_Canvas;
PyObject *const_str_plain_Knight;
PyObject *const_str_plain_Player;
PyObject *const_str_plain_Square;
PyObject *const_str_plain_append;
PyObject *const_str_plain_bishop;
PyObject *const_str_plain_choice;
PyObject *const_str_plain_format;
PyObject *const_str_plain_knight;
PyObject *const_str_plain_locals;
PyObject *const_str_plain_m_f_ps;
PyObject *const_str_plain_m_t_ps;
PyObject *const_str_plain_option;
PyObject *const_str_plain_pieces;
PyObject *const_str_plain_player;
PyObject *const_str_plain_random;
PyObject *const_str_plain_square;
PyObject *const_str_plain_system;
PyObject *const_str_plain_Windows;
PyObject *const_str_plain___all__;
PyObject *const_str_plain___cmp__;
PyObject *const_str_plain___doc__;
PyObject *const_str_plain___str__;
PyObject *const_str_plain_b_check;
PyObject *const_str_plain_compile;
PyObject *const_str_plain_fromSqr;
PyObject *const_str_plain_globVar;
PyObject *const_str_plain_globals;
PyObject *const_str_plain_inspect;
PyObject *const_str_plain_m_f_col;
PyObject *const_str_plain_m_f_row;
PyObject *const_str_plain_m_t_col;
PyObject *const_str_plain_m_t_row;
PyObject *const_str_plain_p_b_Num;
PyObject *const_str_plain_p_w_Num;
PyObject *const_str_plain_r_avail;
PyObject *const_str_plain_removed;
PyObject *const_str_plain_running;
PyObject *const_str_plain_w_check;
PyObject *const_str_plain___dict__;
PyObject *const_str_plain___exit__;
PyObject *const_str_plain___file__;
PyObject *const_str_plain___init__;
PyObject *const_str_plain___iter__;
PyObject *const_str_plain___main__;
PyObject *const_str_plain___name__;
PyObject *const_str_plain___path__;
PyObject *const_str_plain___spec__;
PyObject *const_str_plain_b_pieces;
PyObject *const_str_plain_checkWin;
PyObject *const_str_plain_colCount;
PyObject *const_str_plain_deepcopy;
PyObject *const_str_plain_fromlist;
PyObject *const_str_plain_hasMoves;
PyObject *const_str_plain_last_col;
PyObject *const_str_plain_last_row;
PyObject *const_str_plain_loadSave;
PyObject *const_str_plain_platform;
PyObject *const_str_plain_populate;
PyObject *const_str_plain_readSave;
PyObject *const_str_plain_rowCount;
PyObject *const_str_plain_scanning;
PyObject *const_str_plain_selected;
PyObject *const_str_plain_undoMove;
PyObject *const_str_plain_w_pieces;
PyObject *const_str_plain___class__;
PyObject *const_str_plain___debug__;
PyObject *const_str_plain___enter__;
PyObject *const_str_plain_bytearray;
PyObject *const_str_plain_chooseCol;
PyObject *const_str_plain_chooseRow;
PyObject *const_str_plain_clearSave;
PyObject *const_str_plain_drawBoard;
PyObject *const_str_plain_edgeFound;
PyObject *const_str_plain_firstMove;
PyObject *const_str_plain_metaclass;
PyObject *const_str_plain_noPlayers;
PyObject *const_str_plain_p_b_Moves;
PyObject *const_str_plain_p_b_moves;
PyObject *const_str_plain_p_w_moves;
PyObject *const_str_plain_writeSave;
PyObject *const_str_plain___cached__;
PyObject *const_str_plain___import__;
PyObject *const_str_plain___loader__;
PyObject *const_str_plain___module__;
PyObject *const_str_plain_availMoves;
PyObject *const_str_plain_check_king;
PyObject *const_str_plain_chooseMove;
PyObject *const_str_plain_m_f_p_type;
PyObject *const_str_plain_m_t_p_type;
PyObject *const_str_plain_numPlayers;
PyObject *const_str_plain_pieceFound;
PyObject *const_str_plain_r_b_pieces;
PyObject *const_str_plain_r_w_pieces;
PyObject *const_str_plain___package__;
PyObject *const_str_plain___prepare__;
PyObject *const_str_plain_b_NumPieces;
PyObject *const_str_plain_classmethod;
PyObject *const_str_plain_m_f_p_color;
PyObject *const_str_plain_m_f_p_label;
PyObject *const_str_plain_m_t_p_color;
PyObject *const_str_plain_m_t_p_label;
PyObject *const_str_plain_pieceStatus;
PyObject *const_str_plain_playerCount;
PyObject *const_str_plain_r_avail_Num;
PyObject *const_str_plain_selectError;
PyObject *const_str_plain_startScreen;
PyObject *const_str_plain_typeCounter;
PyObject *const_str_plain_w_NumPieces;
PyObject *const_tuple_str_empty_tuple;
PyObject *const_tuple_str_space_tuple;
PyObject *const_str_plain___builtins__;
PyObject *const_str_plain___internal__;
PyObject *const_str_plain___qualname__;
PyObject *const_str_plain_staticmethod;
PyObject *const_str_plain___metaclass__;
PyObject *const_str_plain_optionCounter;
PyObject *const_str_plain_r_b_NumPieces;
PyObject *const_str_plain_r_w_NumPieces;
PyObject *const_str_plain_removed_color;
PyObject *const_str_plain_removed_label;
PyObject *const_tuple_str_newline_tuple;
PyObject *const_str_plain___orig_bases__;
PyObject *const_str_plain_potenial_moves;
PyObject *const_tuple_str_plain_pc_tuple;
PyObject *const_str_plain___mro_entries__;
PyObject *const_str_plain_resetAvailMoves;
PyObject *const_tuple_str_plain_Pawn_tuple;
PyObject *const_tuple_str_plain_self_tuple;
PyObject *const_str_plain___class_getitem__;
PyObject *const_str_plain_clearMovesHistory;
PyObject *const_tuple_str_plain_Piece_tuple;
PyObject *const_str_plain_mark_invalid_moves;
PyObject *const_str_plain_un_resetAvailMoves;
PyObject *const_tuple_str_plain_Square_tuple;
PyObject *const_str_plain_getouttacheckMessage;
PyObject *const_tuple_str_plain___class___tuple;
PyObject *const_str_plain_chooseAvailableMessage;
PyObject *const_dict_f2db04d3b784bf8416a3b4d843a160af;
PyObject *const_tuple_str_plain_none_str_plain_none_tuple;
PyObject *const_str_digest_493f002a372417c40934628c7463b51d;
PyObject *const_str_digest_cfaa231de8b0f7f99773a653279071b3;
PyObject *const_tuple_3b60237ada9568785e5e34c7223e9a53_tuple;
PyObject *const_tuple_str_digest_493f002a372417c40934628c7463b51d_tuple;
PyObject *const_tuple_str_plain_self_str_plain_color_str_plain_type_tuple;

static void _createGlobalConstants( void )
{
    NUITKA_MAY_BE_UNUSED PyObject *exception_type, *exception_value;
    NUITKA_MAY_BE_UNUSED PyTracebackObject *exception_tb;

#ifdef _MSC_VER
    // Prevent unused warnings in case of simple programs, the attribute
    // NUITKA_MAY_BE_UNUSED doesn't work for MSVC.
    (void *)exception_type; (void *)exception_value; (void *)exception_tb;
#endif

    const_int_0 = PyLong_FromUnsignedLong( 0ul );
    const_str_dot = UNSTREAM_STRING( &constant_bin[ 61 ], 1, 0 );
    const_int_neg_1 = PyLong_FromLong( -1l );
    const_int_pos_1 = PyLong_FromUnsignedLong( 1ul );
    const_int_pos_2 = PyLong_FromUnsignedLong( 2ul );
    const_int_pos_6 = PyLong_FromUnsignedLong( 6ul );
    const_int_pos_7 = PyLong_FromUnsignedLong( 7ul );
    const_int_pos_8 = PyLong_FromUnsignedLong( 8ul );
    const_str_empty = UNSTREAM_STRING( &constant_bin[ 0 ], 0, 0 );
    const_str_space = UNSTREAM_STRING( &constant_bin[ 1 ], 1, 0 );
    const_dict_empty = _PyDict_NewPresized( 0 );
    assert( PyDict_Size( const_dict_empty ) == 0 );
    const_int_pos_16 = PyLong_FromUnsignedLong( 16ul );
    const_int_pos_65 = PyLong_FromUnsignedLong( 65ul );
    const_xrange_0_8 = BUILTIN_XRANGE3( const_int_0, const_int_pos_8, const_int_pos_1 );
    const_bytes_empty = UNSTREAM_BYTES( &constant_bin[ 0 ], 0 );
    const_str_newline = UNSTREAM_STRING( &constant_bin[ 0 ], 1, 0 );
    const_str_plain_Q = UNSTREAM_STRING( &constant_bin[ 689 ], 1, 1 );
    const_str_plain_R = UNSTREAM_STRING( &constant_bin[ 239 ], 1, 1 );
    const_str_plain_W = UNSTREAM_STRING( &constant_bin[ 184 ], 1, 1 );
    const_str_plain_a = UNSTREAM_STRING( &constant_bin[ 9 ], 1, 1 );
    const_str_plain_b = UNSTREAM_STRING( &constant_bin[ 97 ], 1, 1 );
    const_str_plain_c = UNSTREAM_STRING( &constant_bin[ 11 ], 1, 1 );
    const_str_plain_i = UNSTREAM_STRING( &constant_bin[ 55 ], 1, 1 );
    const_str_plain_j = UNSTREAM_STRING( &constant_bin[ 3992 ], 1, 1 );
    const_str_plain_k = UNSTREAM_STRING( &constant_bin[ 196 ], 1, 1 );
    const_str_plain_n = UNSTREAM_STRING( &constant_bin[ 16 ], 1, 1 );
    const_str_plain_r = UNSTREAM_STRING( &constant_bin[ 24 ], 1, 1 );
    const_tuple_empty = PyTuple_New( 0 );
    const_str_plain_am = UNSTREAM_STRING( &constant_bin[ 213 ], 2, 1 );
    const_str_plain_os = UNSTREAM_STRING( &constant_bin[ 5 ], 2, 1 );
    const_str_plain_pc = UNSTREAM_STRING( &constant_bin[ 1430 ], 2, 1 );
    const_str_plain_rb = UNSTREAM_STRING( &constant_bin[ 3993 ], 2, 1 );
    const_str_plain_col = UNSTREAM_STRING( &constant_bin[ 11 ], 3, 1 );
    const_str_plain_des = UNSTREAM_STRING( &constant_bin[ 3995 ], 3, 1 );
    const_str_plain_end = UNSTREAM_STRING( &constant_bin[ 3570 ], 3, 1 );
    const_str_plain_int = UNSTREAM_STRING( &constant_bin[ 1333 ], 3, 1 );
    const_str_plain_len = UNSTREAM_STRING( &constant_bin[ 3998 ], 3, 1 );
    const_str_plain_pop = UNSTREAM_STRING( &constant_bin[ 4001 ], 3, 1 );
    const_str_plain_r_c = UNSTREAM_STRING( &constant_bin[ 4004 ], 3, 1 );
    const_str_plain_row = UNSTREAM_STRING( &constant_bin[ 58 ], 3, 1 );
    const_str_plain_sum = UNSTREAM_STRING( &constant_bin[ 4007 ], 3, 1 );
    const_str_plain_Grid = UNSTREAM_STRING( &constant_bin[ 4010 ], 4, 1 );
    const_str_plain_King = UNSTREAM_STRING( &constant_bin[ 2242 ], 4, 1 );
    const_str_plain_Pawn = UNSTREAM_STRING( &constant_bin[ 2420 ], 4, 1 );
    const_str_plain_Rook = UNSTREAM_STRING( &constant_bin[ 2806 ], 4, 1 );
    const_str_plain_copy = UNSTREAM_STRING( &constant_bin[ 4014 ], 4, 1 );
    const_str_plain_file = UNSTREAM_STRING( &constant_bin[ 4018 ], 4, 1 );
    const_str_plain_iter = UNSTREAM_STRING( &constant_bin[ 4022 ], 4, 1 );
    const_str_plain_king = UNSTREAM_STRING( &constant_bin[ 714 ], 4, 1 );
    const_str_plain_move = UNSTREAM_STRING( &constant_bin[ 101 ], 4, 1 );
    const_str_plain_name = UNSTREAM_STRING( &constant_bin[ 4026 ], 4, 1 );
    const_str_plain_none = UNSTREAM_STRING( &constant_bin[ 4030 ], 4, 1 );
    const_str_plain_open = UNSTREAM_STRING( &constant_bin[ 4034 ], 4, 1 );
    const_str_plain_pawn = UNSTREAM_STRING( &constant_bin[ 523 ], 4, 1 );
    const_str_plain_read = UNSTREAM_STRING( &constant_bin[ 3161 ], 4, 1 );
    const_str_plain_repr = UNSTREAM_STRING( &constant_bin[ 4038 ], 4, 1 );
    const_str_plain_rook = UNSTREAM_STRING( &constant_bin[ 543 ], 4, 1 );
    const_str_plain_scan = UNSTREAM_STRING( &constant_bin[ 2107 ], 4, 1 );
    const_str_plain_self = UNSTREAM_STRING( &constant_bin[ 4042 ], 4, 1 );
    const_str_plain_send = UNSTREAM_STRING( &constant_bin[ 4046 ], 4, 1 );
    const_str_plain_site = UNSTREAM_STRING( &constant_bin[ 4050 ], 4, 1 );
    const_str_plain_turn = UNSTREAM_STRING( &constant_bin[ 1275 ], 4, 1 );
    const_str_plain_type = UNSTREAM_STRING( &constant_bin[ 3428 ], 4, 1 );
    const_str_plain_False = UNSTREAM_STRING( &constant_bin[ 4054 ], 5, 1 );
    const_str_plain_Piece = UNSTREAM_STRING( &constant_bin[ 2631 ], 5, 1 );
    const_str_plain_Queen = UNSTREAM_STRING( &constant_bin[ 2697 ], 5, 1 );
    const_str_plain_black = UNSTREAM_STRING( &constant_bin[ 4059 ], 5, 1 );
    const_str_plain_board = UNSTREAM_STRING( &constant_bin[ 406 ], 5, 1 );
    const_str_plain_bytes = UNSTREAM_STRING( &constant_bin[ 4064 ], 5, 1 );
    const_str_plain_clear = UNSTREAM_STRING( &constant_bin[ 3936 ], 5, 1 );
    const_str_plain_close = UNSTREAM_STRING( &constant_bin[ 4069 ], 5, 1 );
    const_str_plain_color = UNSTREAM_STRING( &constant_bin[ 3081 ], 5, 1 );
    const_str_plain_input = UNSTREAM_STRING( &constant_bin[ 4074 ], 5, 1 );
    const_str_plain_label = UNSTREAM_STRING( &constant_bin[ 3434 ], 5, 1 );
    const_str_plain_level = UNSTREAM_STRING( &constant_bin[ 4079 ], 5, 1 );
    const_str_plain_piece = UNSTREAM_STRING( &constant_bin[ 80 ], 5, 1 );
    const_str_plain_print = UNSTREAM_STRING( &constant_bin[ 4084 ], 5, 1 );
    const_str_plain_queen = UNSTREAM_STRING( &constant_bin[ 435 ], 5, 1 );
    const_str_plain_range = UNSTREAM_STRING( &constant_bin[ 4089 ], 5, 1 );
    const_str_plain_throw = UNSTREAM_STRING( &constant_bin[ 4094 ], 5, 1 );
    const_str_plain_types = UNSTREAM_STRING( &constant_bin[ 4099 ], 5, 1 );
    const_str_plain_uGrid = UNSTREAM_STRING( &constant_bin[ 4104 ], 5, 1 );
    const_str_plain_upper = UNSTREAM_STRING( &constant_bin[ 4109 ], 5, 1 );
    const_str_plain_utils = UNSTREAM_STRING( &constant_bin[ 3738 ], 5, 1 );
    const_str_plain_white = UNSTREAM_STRING( &constant_bin[ 4114 ], 5, 1 );
    const_str_plain_Bishop = UNSTREAM_STRING( &constant_bin[ 2100 ], 6, 1 );
    const_str_plain_Canvas = UNSTREAM_STRING( &constant_bin[ 851 ], 6, 1 );
    const_str_plain_Knight = UNSTREAM_STRING( &constant_bin[ 2338 ], 6, 1 );
    const_str_plain_Player = UNSTREAM_STRING( &constant_bin[ 1440 ], 6, 1 );
    const_str_plain_Square = UNSTREAM_STRING( &constant_bin[ 2990 ], 6, 1 );
    const_str_plain_append = UNSTREAM_STRING( &constant_bin[ 4119 ], 6, 1 );
    const_str_plain_bishop = UNSTREAM_STRING( &constant_bin[ 1131 ], 6, 1 );
    const_str_plain_choice = UNSTREAM_STRING( &constant_bin[ 673 ], 6, 1 );
    const_str_plain_format = UNSTREAM_STRING( &constant_bin[ 4125 ], 6, 1 );
    const_str_plain_knight = UNSTREAM_STRING( &constant_bin[ 220 ], 6, 1 );
    const_str_plain_locals = UNSTREAM_STRING( &constant_bin[ 4131 ], 6, 1 );
    const_str_plain_m_f_ps = UNSTREAM_STRING( &constant_bin[ 4137 ], 6, 1 );
    const_str_plain_m_t_ps = UNSTREAM_STRING( &constant_bin[ 4143 ], 6, 1 );
    const_str_plain_option = UNSTREAM_STRING( &constant_bin[ 3674 ], 6, 1 );
    const_str_plain_pieces = UNSTREAM_STRING( &constant_bin[ 798 ], 6, 1 );
    const_str_plain_player = UNSTREAM_STRING( &constant_bin[ 261 ], 6, 1 );
    const_str_plain_random = UNSTREAM_STRING( &constant_bin[ 4149 ], 6, 1 );
    const_str_plain_square = UNSTREAM_STRING( &constant_bin[ 774 ], 6, 1 );
    const_str_plain_system = UNSTREAM_STRING( &constant_bin[ 4155 ], 6, 1 );
    const_str_plain_Windows = UNSTREAM_STRING( &constant_bin[ 4161 ], 7, 1 );
    const_str_plain___all__ = UNSTREAM_STRING( &constant_bin[ 4168 ], 7, 1 );
    const_str_plain___cmp__ = UNSTREAM_STRING( &constant_bin[ 4175 ], 7, 1 );
    const_str_plain___doc__ = UNSTREAM_STRING( &constant_bin[ 4182 ], 7, 1 );
    const_str_plain___str__ = UNSTREAM_STRING( &constant_bin[ 2118 ], 7, 1 );
    const_str_plain_b_check = UNSTREAM_STRING( &constant_bin[ 3750 ], 7, 1 );
    const_str_plain_compile = UNSTREAM_STRING( &constant_bin[ 4189 ], 7, 1 );
    const_str_plain_fromSqr = UNSTREAM_STRING( &constant_bin[ 4196 ], 7, 1 );
    const_str_plain_globVar = UNSTREAM_STRING( &constant_bin[ 1933 ], 7, 1 );
    const_str_plain_globals = UNSTREAM_STRING( &constant_bin[ 4203 ], 7, 1 );
    const_str_plain_inspect = UNSTREAM_STRING( &constant_bin[ 4210 ], 7, 1 );
    const_str_plain_m_f_col = UNSTREAM_STRING( &constant_bin[ 4217 ], 7, 1 );
    const_str_plain_m_f_row = UNSTREAM_STRING( &constant_bin[ 4224 ], 7, 1 );
    const_str_plain_m_t_col = UNSTREAM_STRING( &constant_bin[ 4231 ], 7, 1 );
    const_str_plain_m_t_row = UNSTREAM_STRING( &constant_bin[ 4238 ], 7, 1 );
    const_str_plain_p_b_Num = UNSTREAM_STRING( &constant_bin[ 4245 ], 7, 1 );
    const_str_plain_p_w_Num = UNSTREAM_STRING( &constant_bin[ 4252 ], 7, 1 );
    const_str_plain_r_avail = UNSTREAM_STRING( &constant_bin[ 3540 ], 7, 1 );
    const_str_plain_removed = UNSTREAM_STRING( &constant_bin[ 4259 ], 7, 1 );
    const_str_plain_running = UNSTREAM_STRING( &constant_bin[ 4266 ], 7, 1 );
    const_str_plain_w_check = UNSTREAM_STRING( &constant_bin[ 3890 ], 7, 1 );
    const_str_plain___dict__ = UNSTREAM_STRING( &constant_bin[ 4273 ], 8, 1 );
    const_str_plain___exit__ = UNSTREAM_STRING( &constant_bin[ 4281 ], 8, 1 );
    const_str_plain___file__ = UNSTREAM_STRING( &constant_bin[ 4289 ], 8, 1 );
    const_str_plain___init__ = UNSTREAM_STRING( &constant_bin[ 2012 ], 8, 1 );
    const_str_plain___iter__ = UNSTREAM_STRING( &constant_bin[ 4297 ], 8, 1 );
    const_str_plain___main__ = UNSTREAM_STRING( &constant_bin[ 4305 ], 8, 1 );
    const_str_plain___name__ = UNSTREAM_STRING( &constant_bin[ 4313 ], 8, 1 );
    const_str_plain___path__ = UNSTREAM_STRING( &constant_bin[ 4321 ], 8, 1 );
    const_str_plain___spec__ = UNSTREAM_STRING( &constant_bin[ 4329 ], 8, 1 );
    const_str_plain_b_pieces = UNSTREAM_STRING( &constant_bin[ 4337 ], 8, 1 );
    const_str_plain_checkWin = UNSTREAM_STRING( &constant_bin[ 4345 ], 8, 1 );
    const_str_plain_colCount = UNSTREAM_STRING( &constant_bin[ 4353 ], 8, 1 );
    const_str_plain_deepcopy = UNSTREAM_STRING( &constant_bin[ 4361 ], 8, 1 );
    const_str_plain_fromlist = UNSTREAM_STRING( &constant_bin[ 4369 ], 8, 1 );
    const_str_plain_hasMoves = UNSTREAM_STRING( &constant_bin[ 4377 ], 8, 1 );
    const_str_plain_last_col = UNSTREAM_STRING( &constant_bin[ 4385 ], 8, 1 );
    const_str_plain_last_row = UNSTREAM_STRING( &constant_bin[ 4393 ], 8, 1 );
    const_str_plain_loadSave = UNSTREAM_STRING( &constant_bin[ 4401 ], 8, 1 );
    const_str_plain_platform = UNSTREAM_STRING( &constant_bin[ 4409 ], 8, 1 );
    const_str_plain_populate = UNSTREAM_STRING( &constant_bin[ 4417 ], 8, 1 );
    const_str_plain_readSave = UNSTREAM_STRING( &constant_bin[ 4425 ], 8, 1 );
    const_str_plain_rowCount = UNSTREAM_STRING( &constant_bin[ 4433 ], 8, 1 );
    const_str_plain_scanning = UNSTREAM_STRING( &constant_bin[ 4441 ], 8, 1 );
    const_str_plain_selected = UNSTREAM_STRING( &constant_bin[ 4449 ], 8, 1 );
    const_str_plain_undoMove = UNSTREAM_STRING( &constant_bin[ 4457 ], 8, 1 );
    const_str_plain_w_pieces = UNSTREAM_STRING( &constant_bin[ 4465 ], 8, 1 );
    const_str_plain___class__ = UNSTREAM_STRING( &constant_bin[ 4473 ], 9, 1 );
    const_str_plain___debug__ = UNSTREAM_STRING( &constant_bin[ 4482 ], 9, 1 );
    const_str_plain___enter__ = UNSTREAM_STRING( &constant_bin[ 4491 ], 9, 1 );
    const_str_plain_bytearray = UNSTREAM_STRING( &constant_bin[ 4500 ], 9, 1 );
    const_str_plain_chooseCol = UNSTREAM_STRING( &constant_bin[ 4509 ], 9, 1 );
    const_str_plain_chooseRow = UNSTREAM_STRING( &constant_bin[ 4518 ], 9, 1 );
    const_str_plain_clearSave = UNSTREAM_STRING( &constant_bin[ 4527 ], 9, 1 );
    const_str_plain_drawBoard = UNSTREAM_STRING( &constant_bin[ 4536 ], 9, 1 );
    const_str_plain_edgeFound = UNSTREAM_STRING( &constant_bin[ 4545 ], 9, 1 );
    const_str_plain_firstMove = UNSTREAM_STRING( &constant_bin[ 4554 ], 9, 1 );
    const_str_plain_metaclass = UNSTREAM_STRING( &constant_bin[ 4563 ], 9, 1 );
    const_str_plain_noPlayers = UNSTREAM_STRING( &constant_bin[ 4572 ], 9, 1 );
    const_str_plain_p_b_Moves = UNSTREAM_STRING( &constant_bin[ 4581 ], 9, 1 );
    const_str_plain_p_b_moves = UNSTREAM_STRING( &constant_bin[ 4590 ], 9, 1 );
    const_str_plain_p_w_moves = UNSTREAM_STRING( &constant_bin[ 4599 ], 9, 1 );
    const_str_plain_writeSave = UNSTREAM_STRING( &constant_bin[ 4608 ], 9, 1 );
    const_str_plain___cached__ = UNSTREAM_STRING( &constant_bin[ 4617 ], 10, 1 );
    const_str_plain___import__ = UNSTREAM_STRING( &constant_bin[ 4627 ], 10, 1 );
    const_str_plain___loader__ = UNSTREAM_STRING( &constant_bin[ 4637 ], 10, 1 );
    const_str_plain___module__ = UNSTREAM_STRING( &constant_bin[ 4647 ], 10, 1 );
    const_str_plain_availMoves = UNSTREAM_STRING( &constant_bin[ 413 ], 10, 1 );
    const_str_plain_check_king = UNSTREAM_STRING( &constant_bin[ 4657 ], 10, 1 );
    const_str_plain_chooseMove = UNSTREAM_STRING( &constant_bin[ 4667 ], 10, 1 );
    const_str_plain_m_f_p_type = UNSTREAM_STRING( &constant_bin[ 4677 ], 10, 1 );
    const_str_plain_m_t_p_type = UNSTREAM_STRING( &constant_bin[ 4687 ], 10, 1 );
    const_str_plain_numPlayers = UNSTREAM_STRING( &constant_bin[ 4697 ], 10, 1 );
    const_str_plain_pieceFound = UNSTREAM_STRING( &constant_bin[ 4707 ], 10, 1 );
    const_str_plain_r_b_pieces = UNSTREAM_STRING( &constant_bin[ 4717 ], 10, 1 );
    const_str_plain_r_w_pieces = UNSTREAM_STRING( &constant_bin[ 4727 ], 10, 1 );
    const_str_plain___package__ = UNSTREAM_STRING( &constant_bin[ 4737 ], 11, 1 );
    const_str_plain___prepare__ = UNSTREAM_STRING( &constant_bin[ 4748 ], 11, 1 );
    const_str_plain_b_NumPieces = UNSTREAM_STRING( &constant_bin[ 4759 ], 11, 1 );
    const_str_plain_classmethod = UNSTREAM_STRING( &constant_bin[ 4770 ], 11, 1 );
    const_str_plain_m_f_p_color = UNSTREAM_STRING( &constant_bin[ 4781 ], 11, 1 );
    const_str_plain_m_f_p_label = UNSTREAM_STRING( &constant_bin[ 4792 ], 11, 1 );
    const_str_plain_m_t_p_color = UNSTREAM_STRING( &constant_bin[ 4803 ], 11, 1 );
    const_str_plain_m_t_p_label = UNSTREAM_STRING( &constant_bin[ 4814 ], 11, 1 );
    const_str_plain_pieceStatus = UNSTREAM_STRING( &constant_bin[ 4825 ], 11, 1 );
    const_str_plain_playerCount = UNSTREAM_STRING( &constant_bin[ 4836 ], 11, 1 );
    const_str_plain_r_avail_Num = UNSTREAM_STRING( &constant_bin[ 4847 ], 11, 1 );
    const_str_plain_selectError = UNSTREAM_STRING( &constant_bin[ 4858 ], 11, 1 );
    const_str_plain_startScreen = UNSTREAM_STRING( &constant_bin[ 4869 ], 11, 1 );
    const_str_plain_typeCounter = UNSTREAM_STRING( &constant_bin[ 4880 ], 11, 1 );
    const_str_plain_w_NumPieces = UNSTREAM_STRING( &constant_bin[ 4891 ], 11, 1 );
    const_tuple_str_empty_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_empty_tuple, 0, const_str_empty ); Py_INCREF( const_str_empty );
    const_tuple_str_space_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_space_tuple, 0, const_str_space ); Py_INCREF( const_str_space );
    const_str_plain___builtins__ = UNSTREAM_STRING( &constant_bin[ 4902 ], 12, 1 );
    const_str_plain___internal__ = UNSTREAM_STRING( &constant_bin[ 4914 ], 12, 1 );
    const_str_plain___qualname__ = UNSTREAM_STRING( &constant_bin[ 4926 ], 12, 1 );
    const_str_plain_staticmethod = UNSTREAM_STRING( &constant_bin[ 4938 ], 12, 1 );
    const_str_plain___metaclass__ = UNSTREAM_STRING( &constant_bin[ 4950 ], 13, 1 );
    const_str_plain_optionCounter = UNSTREAM_STRING( &constant_bin[ 4963 ], 13, 1 );
    const_str_plain_r_b_NumPieces = UNSTREAM_STRING( &constant_bin[ 4976 ], 13, 1 );
    const_str_plain_r_w_NumPieces = UNSTREAM_STRING( &constant_bin[ 4989 ], 13, 1 );
    const_str_plain_removed_color = UNSTREAM_STRING( &constant_bin[ 5002 ], 13, 1 );
    const_str_plain_removed_label = UNSTREAM_STRING( &constant_bin[ 5015 ], 13, 1 );
    const_tuple_str_newline_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_newline_tuple, 0, const_str_newline ); Py_INCREF( const_str_newline );
    const_str_plain___orig_bases__ = UNSTREAM_STRING( &constant_bin[ 5028 ], 14, 1 );
    const_str_plain_potenial_moves = UNSTREAM_STRING( &constant_bin[ 5042 ], 14, 1 );
    const_tuple_str_plain_pc_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_pc_tuple, 0, const_str_plain_pc ); Py_INCREF( const_str_plain_pc );
    const_str_plain___mro_entries__ = UNSTREAM_STRING( &constant_bin[ 5056 ], 15, 1 );
    const_str_plain_resetAvailMoves = UNSTREAM_STRING( &constant_bin[ 5071 ], 15, 1 );
    const_tuple_str_plain_Pawn_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Pawn_tuple, 0, const_str_plain_Pawn ); Py_INCREF( const_str_plain_Pawn );
    const_tuple_str_plain_self_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    const_str_plain___class_getitem__ = UNSTREAM_STRING( &constant_bin[ 5086 ], 17, 1 );
    const_str_plain_clearMovesHistory = UNSTREAM_STRING( &constant_bin[ 5103 ], 17, 1 );
    const_tuple_str_plain_Piece_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Piece_tuple, 0, const_str_plain_Piece ); Py_INCREF( const_str_plain_Piece );
    const_str_plain_mark_invalid_moves = UNSTREAM_STRING( &constant_bin[ 5120 ], 18, 1 );
    const_str_plain_un_resetAvailMoves = UNSTREAM_STRING( &constant_bin[ 5138 ], 18, 1 );
    const_tuple_str_plain_Square_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Square_tuple, 0, const_str_plain_Square ); Py_INCREF( const_str_plain_Square );
    const_str_plain_getouttacheckMessage = UNSTREAM_STRING( &constant_bin[ 5156 ], 20, 1 );
    const_tuple_str_plain___class___tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain___class___tuple, 0, const_str_plain___class__ ); Py_INCREF( const_str_plain___class__ );
    const_str_plain_chooseAvailableMessage = UNSTREAM_STRING( &constant_bin[ 5176 ], 22, 1 );
    const_dict_f2db04d3b784bf8416a3b4d843a160af = _PyDict_NewPresized( 1 );
    PyDict_SetItem( const_dict_f2db04d3b784bf8416a3b4d843a160af, const_str_plain_end, const_str_empty );
    assert( PyDict_Size( const_dict_f2db04d3b784bf8416a3b4d843a160af ) == 1 );
    const_tuple_str_plain_none_str_plain_none_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_none_str_plain_none_tuple, 0, const_str_plain_none ); Py_INCREF( const_str_plain_none );
    PyTuple_SET_ITEM( const_tuple_str_plain_none_str_plain_none_tuple, 1, const_str_plain_none ); Py_INCREF( const_str_plain_none );
    const_str_digest_493f002a372417c40934628c7463b51d = UNSTREAM_STRING( &constant_bin[ 5198 ], 10, 0 );
    const_str_digest_cfaa231de8b0f7f99773a653279071b3 = UNSTREAM_STRING( &constant_bin[ 5208 ], 67, 0 );
    const_tuple_3b60237ada9568785e5e34c7223e9a53_tuple = PyTuple_New( 6 );
    PyTuple_SET_ITEM( const_tuple_3b60237ada9568785e5e34c7223e9a53_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_3b60237ada9568785e5e34c7223e9a53_tuple, 1, const_str_plain_availMoves ); Py_INCREF( const_str_plain_availMoves );
    PyTuple_SET_ITEM( const_tuple_3b60237ada9568785e5e34c7223e9a53_tuple, 2, const_str_plain_optionCounter ); Py_INCREF( const_str_plain_optionCounter );
    PyTuple_SET_ITEM( const_tuple_3b60237ada9568785e5e34c7223e9a53_tuple, 3, const_str_plain_pieceFound ); Py_INCREF( const_str_plain_pieceFound );
    PyTuple_SET_ITEM( const_tuple_3b60237ada9568785e5e34c7223e9a53_tuple, 4, const_str_plain_rowCount ); Py_INCREF( const_str_plain_rowCount );
    PyTuple_SET_ITEM( const_tuple_3b60237ada9568785e5e34c7223e9a53_tuple, 5, const_str_plain_colCount ); Py_INCREF( const_str_plain_colCount );
    const_tuple_str_digest_493f002a372417c40934628c7463b51d_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_digest_493f002a372417c40934628c7463b51d_tuple, 0, const_str_digest_493f002a372417c40934628c7463b51d ); Py_INCREF( const_str_digest_493f002a372417c40934628c7463b51d );
    const_tuple_str_plain_self_str_plain_color_str_plain_type_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_color_str_plain_type_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_color_str_plain_type_tuple, 1, const_str_plain_color ); Py_INCREF( const_str_plain_color );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_color_str_plain_type_tuple, 2, const_str_plain_type ); Py_INCREF( const_str_plain_type );

#if _NUITKA_EXE
    /* Set the "sys.executable" path to the original CPython executable. */
    PySys_SetObject(
        (char *)"executable",
        const_str_digest_cfaa231de8b0f7f99773a653279071b3
    );
#endif
}

// In debug mode we can check that the constants were not tampered with in any
// given moment. We typically do it at program exit, but we can add extra calls
// for sanity.
#ifndef __NUITKA_NO_ASSERT__
void checkGlobalConstants( void )
{

}
#endif

void createGlobalConstants( void )
{
    if ( _sentinel_value == NULL )
    {
#if PYTHON_VERSION < 300
        _sentinel_value = PyCObject_FromVoidPtr( NULL, NULL );
#else
        // The NULL value is not allowed for a capsule, so use something else.
        _sentinel_value = PyCapsule_New( (void *)27, "sentinel", NULL );
#endif
        assert( _sentinel_value );

        _createGlobalConstants();
    }
}
